_target_: lambo.models.deep_ensemble.DeepEnsemble
model: mCNN
model_kwargs:
  embed_dim: 64
  latent_dim: 16
  out_dim: ${task.obj_dim}
  kernel_size: 9
  p: 2e-3
  layernorm: True
  max_len: ${task.max_len}
  max_len_delta: 0

tokenizer: ${tokenizer}
ensemble_size: 8
num_epochs: 256
eval_period: 1
bootstrap_ratio: null
min_num_train: 128
weight_decay: 5e-5
holdout_ratio: 0.1
early_stopping: True
lr: 1e-3
bs: 32
patience: 32
max_shift: 0
mask_size: 0